### ISSUE TITLE
The Packs not working.

### ISSUE THREAD

**Issue by TheClashFruit** [Jinzulen/DEmojiJS#6]
Gives me this error:
      DEmojiJS.Packs().then(Packs => {
               ^

TypeError: DEmojiJS.Packs is not a function
    at Client.<anonymous> (C:\Users\User\Desktop\discord.emoji\bot.js:101:16)
    at Client.emit (events.js:210:5)
    at MessageCreateAction.handle (C:\Users\User\Desktop\discord.emoji\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\User\Desktop\discord.emoji\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\User\Desktop\discord.emoji\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\User\Desktop\discord.emoji\node_modules\discord.js\src\client\websocket\WebSocketShard.js:435:22)
    at WebSocketShard.onMessage (C:\Users\User\Desktop\discord.emoji\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\User\Desktop\discord.emoji\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:210:5)
    at Receiver.receiverOnMessage (C:\Users\User\Desktop\discord.emoji\node_modules\ws\lib\websocket.js:801:20)

**Comment by Jinzulen** [comment]
Hello, packs were introduced in v1.3.0, please check that you're running the latest version of DEmojiJS, if not, update accordingly.

**Comment by Jinzulen** [comment]
@TheClashFruit Hello, packs were introduced in v1.3.0, please check that you're running the latest version of DEmojiJS, if not, update accordingly.

Please note that sometimes, NPM would notify you that it has indeed updated a certain package when in reality, the update didn't take effect, if this happens, delete the _demojijs_ package from your _node_modules_ directory and re-install it using the command: _npm i demojijs@latest_
